# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_calc_dist_reef
#'
#' @description Rcpp calc dist reef
#'
#' @param seafloor Matrix with coordinates of cells.
#' @param coords_reef 2-column Matrix with coordinates of AR.
#' @param extent Vector with dimension in x and y direction.
#' @param torus If TRUE the distance will be calculated using a torus.
#'
#' @details
#' Rcpp implementation to calculate distance to reef cells. Returns vector with
#' distance for each cell to reef
#'
#' @return vector
#'
#' @aliases rcpp_calc_dist_reef
#' @rdname rcpp_calc_dist_reef
#'
#' @keywords export
rcpp_calc_dist_reef <- function(seafloor, coords_reef, extent, torus = FALSE) {
    .Call(`_arrR_rcpp_calc_dist_reef`, seafloor, coords_reef, extent, torus)
}

#' rcpp_calc_fishpop_growth
#'
#' @description Rcpp calc growth
#'
#' @param fishpop,fishpop_track Matrix with fishpop values and starting population.
#' @param seafloor Matrix with seafloor values.
#' @param fish_id,cell_id Vector with id of fish and corresponding cell ids.
#' @param pop_k,pop_linf,pop_a,pop_b Numeric with parameters.
#' @param pop_n_body,pop_max_reserves,pop_want_reserves,min_per_i Numeric with parameters.
#'
#' @details
#' Rcpp mplementation to calculate growth of fish individuals.
#'
#' @return void
#'
#' @aliases rcpp_calc_fishpop_growth
#' @rdname rcpp_calc_fishpop_growth
#'
#' @export
rcpp_calc_fishpop_growth <- function(fishpop, fishpop_track, seafloor, fish_id, cell_id, pop_k, pop_linf, pop_a, pop_b, pop_n_body, pop_max_reserves, pop_want_reserves, min_per_i) {
    invisible(.Call(`_arrR_rcpp_calc_fishpop_growth`, fishpop, fishpop_track, seafloor, fish_id, cell_id, pop_k, pop_linf, pop_a, pop_b, pop_n_body, pop_max_reserves, pop_want_reserves, min_per_i))
}

#' rcpp_calc_mineralization
#'
#' @description Rcpp calculate mineralization
#'
#' @param seafloor Matrix with seafloor values.
#' @param detritus_dead_ratio,detritus_mineralization seafloor Numeric with parameters.
#'
#' @details
#' Rcpp implementation to calculate detritus miniralization.
#'
#' @return void
#'
#' @aliases rcpp_calc_mineralization
#' @rdname rcpp_calc_mineralization
#'
#' @keywords export
rcpp_calc_mineralization <- function(seafloor, detritus_dead_ratio, detritus_mineralization) {
    invisible(.Call(`_arrR_rcpp_calc_mineralization`, seafloor, detritus_dead_ratio, detritus_mineralization))
}

#' rcpp_calc_mortality
#'
#' @description Rcpp create rebirth
#'
#' @param fishpop,fishpop_track Matrix with fishpop and starting fishpop values.
#' @param seafloor Matrix with seafloor values.
#' @param fish_id,cell_id Vector with id of fish and corresponding cell ids.
#' @param pop_linf,pop_n_body,pop_want_reserves Numeric with parameters.
#'
#' @details
#' Rcpp implementation to create new individual after mortality event.
#'
#' @return void
#'
#' @aliases rcpp_calc_mortality
#' @rdname rcpp_calc_mortality
#'
#' @export
rcpp_calc_mortality <- function(fishpop, fishpop_track, seafloor, fish_id, cell_id, pop_linf, pop_n_body, pop_want_reserves) {
    invisible(.Call(`_arrR_rcpp_calc_mortality`, fishpop, fishpop_track, seafloor, fish_id, cell_id, pop_linf, pop_n_body, pop_want_reserves))
}

#' rcpp_calc_respiration
#'
#' @description Rcpp calculate respration
#'
#' @param fishpop Matrix with fishpop values.
#' @param resp_intercept,resp_slope Numeric with parameters.
#' @param resp_temp_low,resp_temp_max,resp_temp_optm Numeric with parameters.
#' @param water_temp,min_per_i, Numeric with parameters.
#'
#' @details
#' Rcpp implementation to calculate respiration of fish individuals.
#'
#' @return void
#'
#' @aliases rcpp_calc_respiration
#' @rdname rcpp_calc_respiration
#'
#' @export
rcpp_calc_respiration <- function(fishpop, resp_intercept, resp_slope, resp_temp_low, resp_temp_max, resp_temp_optm, water_temp, min_per_i) {
    invisible(.Call(`_arrR_rcpp_calc_respiration`, fishpop, resp_intercept, resp_slope, resp_temp_low, resp_temp_max, resp_temp_optm, water_temp, min_per_i))
}

#' rcpp_convert_nutr
#'
#' @description Rcpp convert nutrients
#'
#' @param x Numeric with nutrient amount.
#' @param to String to specify in which unit to convert.
#'
#' @details
#' Rcpp implementation to convert nutrients between g and umol.
#'
#' @return double
#'
#' @aliases rcpp_convert_nutr
#' @rdname rcpp_convert_nutr
#'
#' @keywords export
rcpp_convert_nutr <- function(x, to) {
    .Call(`_arrR_rcpp_convert_nutr`, x, to)
}

#' rcpp_calc_nutr_uptake
#'
#' @description Rcpp calculate nutrient uptake
#'
#' @param nutrients,biomass Numeric with nutrient and biomass amount of cell.
#' @param v_max,k_m,time_frac Numeric with parameters
#'
#' @details
#' Rcpp implementation to calculate nutrient uptake of cell
#'
#' @return double
#'
#' @aliases rcpp_calc_nutr_uptake
#' @rdname rcpp_calc_nutr_uptake
#'
#' @keywords export
rcpp_calc_nutr_uptake <- function(nutrients, biomass, v_max, k_m, time_frac) {
    .Call(`_arrR_rcpp_calc_nutr_uptake`, nutrients, biomass, v_max, k_m, time_frac)
}

#' rcpp_calc_seagrass_growth
#'
#' @description Rcpp calc seagrass growth
#'
#' @param seafloor Matrix with seafloor values.
#' @param cells_reef Vector with id of reef cells.
#' @param bg_v_max,bg_k_m,bg_gamma,ag_v_max,ag_k_m,ag_gamma Numeric with uptake parameters.
#' @param bg_biomass_max,bg_biomass_min,ag_biomass_max,ag_biomass_min Numerich with biomass values and parameters.
#' @param detritus_ratio,bg_thres,min_per_i Numerich with various parameters.
#'
#' @details
#' Rcpp implementation to calculate seagrass growth.
#'
#' @return void
#'
#' @aliases rcpp_calc_seagrass_growth
#' @rdname rcpp_calc_seagrass_growth
#'
#' @keywords export
rcpp_calc_seagrass_growth <- function(seafloor, cells_reef, bg_v_max, bg_k_m, bg_gamma, ag_v_max, ag_k_m, ag_gamma, bg_biomass_max, bg_biomass_min, ag_biomass_max, ag_biomass_min, detritus_ratio, bg_thres, min_per_i) {
    invisible(.Call(`_arrR_rcpp_calc_seagrass_growth`, seafloor, cells_reef, bg_v_max, bg_k_m, bg_gamma, ag_v_max, ag_k_m, ag_gamma, bg_biomass_max, bg_biomass_min, ag_biomass_max, ag_biomass_min, detritus_ratio, bg_thres, min_per_i))
}

#' rcpp_cell_from_xy
#'
#' @description Rcpp get cell id from xy
#'
#' @param coords Vector with coordinates.
#' @param dimensions Vector with number or rows and cols
#' @param extent Vector with extent (xmin, xmax, ymin, ymax).
#'
#' @details
#' Rcpp implementation to get cell id from xy coordinate. Allows only one coordinate
#' pair at a time.
#'
#' @references
#' Code adapted from Robert J. Hijmans (2020). raster: Geographic Data Analysis
#' and Modeling. R package version 3.4-5. https://CRAN.R-project.org/package=raster
#'
#' @return int
#'
#' @aliases rcpp_cell_from_xy
#' @rdname rcpp_cell_from_xy
#'
#' @keywords export
rcpp_cell_from_xy <- function(coords, dimensions, extent) {
    .Call(`_arrR_rcpp_cell_from_xy`, coords, dimensions, extent)
}

#' rcpp_diffuse_values
#'
#' @description Rcpp diffuse values
#'
#' @param seafloor Matrix with seafloor values.
#' @param cell_adj Matrix with cell adjacencies.
#' @param nutrients_diffusion,detritus_diffusion,detritus_dead_diffusion Numeric with parameters.
#'
#' @details
#' Rcpp implementation to diffuse seafloor values between neighbouring cells.
#'
#' @return void
#'
#' @aliases rcpp_diffuse_values
#' @rdname rcpp_diffuse_values
#'
#' @export
rcpp_diffuse_values <- function(seafloor, cell_adj, nutrients_diffusion, detritus_diffusion, detritus_dead_diffusion) {
    invisible(.Call(`_arrR_rcpp_diffuse_values`, seafloor, cell_adj, nutrients_diffusion, detritus_diffusion, detritus_dead_diffusion))
}

#' rcpp_modify_degree
#'
#' @description Rcpp modify degree
#'
#' @param x Numeric with current angle in degree.
#' @param y Numerich with change of degree (negative or positive).
#'
#' @details
#' Rcpp implementation to substract or add degree to angle. Makes sure angles are
#' between 0 <= x <= 360.
#'
#' @return double
#'
#' @aliases rcpp_modify_degree
#' @rdname rcpp_modify_degree
#'
#' @keywords export
rcpp_modify_degree <- function(x, y) {
    .Call(`_arrR_rcpp_modify_degree`, x, y)
}

#' rcpp_move_fishpop
#'
#' @description Rcpp move fish population
#'
#' @param fishpop Matrix with fishpop values.
#' @param reef_dist Vector with distance to reef of each cell.
#' @param move_dist Vector with move distance of fish individuals.
#' @param pop_mean_move Double with mean movement parameter.
#' @param pop_visibility Double with "sight" distance of fish.
#' @param reef_attraction Bool if attracted towards reef.
#' @param extent Vector with extent (xmin,xmax,ymin,ymax).
#' @param dimensions Vector with dimensions (nrow, ncol).
#' @param pop_mean_move Numeric with parameter.
#'
#' @details
#' Rcpp implementation to move fish individuals depending on move distance and
#' heading value.
#'
#' @return void
#'
#' @aliases rcpp_move_fishpop
#' @rdname rcpp_move_fishpop
#'
#' @export
rcpp_move_fishpop <- function(fishpop, reef_dist, move_dist, pop_mean_move, pop_visibility, reef_attraction, extent, dimensions) {
    invisible(.Call(`_arrR_rcpp_move_fishpop`, fishpop, reef_dist, move_dist, pop_mean_move, pop_visibility, reef_attraction, extent, dimensions))
}

#' rcpp_translate_torus
#'
#' @description Rcpp translate torus
#'
#' @param coords Vector with coordinates.
#' @param extent Vector with extent (xmin,xmax,ymin,ymax).
#'
#' @details
#' Rcpp implementation to translate coordinates if they exceed extent.
#' "KSM" notes from Katrina to help understand code
#' "Q" questions Katrina has for Max
#' "C" code to add
#' @return void
#'
#' @aliases rcpp_translate_torus
#' @rdname rcpp_translate_torus
#'
#' @keywords export
rcpp_translate_torus <- function(coords, extent) {
    .Call(`_arrR_rcpp_translate_torus`, coords, extent)
}

