# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_calc_dist_reef
#'
#' @description Internal rcpp function
#'
#' @param seafloor Matrix.
#' @param coords_reef 2-column matrix with coordinates of AR.
#' @param extent Vector with dimension in x and y direction.
#' @param torus If TRUE the distance will be calculated using a torus.
#'
#' @details
#' Internal function calculate distance to reef cells.
#'
#' @return matrix
#'
#' @aliases rcpp_calc_dist_reef
#' @rdname rcpp_calc_dist_reef
#'
#' @keywords internal
#'
#' @keywords export
rcpp_calc_dist_reef <- function(seafloor, coords_reef, extent, torus = FALSE) {
    .Call(`_arrR_rcpp_calc_dist_reef`, seafloor, coords_reef, extent, torus)
}

#' rcpp_calc_growth
#'
#' @description Rcpp calc growth
#'
#' @param fishpop Matrix with fishpop values.
#' @param seafloor Matrix with seafloor values.
#' @param growth_values Matrix with growth values.
#' @param pop_n_body,pop_max_reserves,min_per_i Numeric with parameters.
#'
#' @details
#' \code{Rcpp} implementation of to calculate growth.
#'
#' @return Matrix
#'
#' @name rcpp_calc_growth
#'
#' @export
rcpp_calc_growth <- function(fishpop, fishpop_track, seafloor, cell_id, growth_values, pop_n_body, pop_max_reserves, pop_want_reserves, min_per_i) {
    invisible(.Call(`_arrR_rcpp_calc_growth`, fishpop, fishpop_track, seafloor, cell_id, growth_values, pop_n_body, pop_max_reserves, pop_want_reserves, min_per_i))
}

#' rcpp_diffuse_values
#'
#' @description Rcpp function to diffuse seafloor values
#'
#' @param seafloor_values Matrix with seafloor values.
#' @param cell_adj Matrix with cell adjacencies.
#' @param nutrients_diffusion,detritus_diffusion,detritus_dead_diffusion Numeric with parameters.
#'
#' @details
#' \code{Rcpp} implementation of to diffuse nutrients.
#'
#' @return Matrix
#'
#' @name rcpp_diffuse_values
#'
#' @export
rcpp_diffuse_values <- function(seafloor_values, cell_adj, nutrients_diffusion, detritus_diffusion, detritus_dead_diffusion) {
    .Call(`_arrR_rcpp_diffuse_values`, seafloor_values, cell_adj, nutrients_diffusion, detritus_diffusion, detritus_dead_diffusion)
}

