# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_calc_dist_fish
#'
#' @description Internal rcpp function
#'
#' @param fish_population 2-column matrix with coordinates of individual fish.
#' @param coords_reef 2-column matrix with coordinates of AR.
#'
#' @details
#' Internal function calculate distance to reef cells.
#'
#' @return matrix
#'
#' @aliases rcpp_calc_dist_fish
#' @rdname rcpp_calc_dist_fish
#'
#' @keywords internal
#'
#' @keywords export
rcpp_calc_dist_fish <- function(fish_population, coords_reef) {
    .Call(`_coRal_rcpp_calc_dist_fish`, fish_population, coords_reef)
}

#' rcpp_calc_dist_reef
#'
#' @description Internal rcpp function
#'
#' @param fish_population 2-column matrix with coordinates of individual fish.
#' @param coords_reef 2-column matrix with coordinates of AR.
#' @param torus If TRUE the distance will be calculated using a torus.
#' @param extent Vector with dimension in x and y direction.
#'
#' @details
#' Internal function calculate distance to reef cells.
#'
#' @return matrix
#'
#' @aliases rcpp_calc_dist_reef
#' @rdname rcpp_calc_dist_reef
#'
#' @keywords internal
#'
#' @keywords export
rcpp_calc_dist_reef <- function(seafloor, coords_reef, extent, torus = FALSE) {
    .Call(`_coRal_rcpp_calc_dist_reef`, seafloor, coords_reef, extent, torus)
}

#' rcpp_diffuse_values
#'
#' @description Rcpp sample function
#'
#' @param x Vector of elements to sample from.
#' @param n Size of the sample.
#' @param replace Sample with replacement.
#'
#' @details
#' \code{Rcpp} implementation of the \code{sample} function.
#'
#' @seealso
#' \code{\link{sample}}
#'
#' @return vector
#'
#' @name rcpp_diffuse_values
#' @export
rcpp_diffuse_values <- function(seafloor_values, cell_adj, wc_diffusion, detritus_diffusion, detritus_dead_diffusion) {
    .Call(`_coRal_rcpp_diffuse_values`, seafloor_values, cell_adj, wc_diffusion, detritus_diffusion, detritus_dead_diffusion)
}

